<?xml version = "1.0" ?>
<?xml:stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Model_Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Model_Simulation CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Published CDATA #IMPLIED>
  <!ATTLIST ROW Publisher CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate" Caption="LatestRevisionDate" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote" Caption="LatestRevisionNote" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="Model_Signal_Integrity" Caption="Model:Signal Integrity" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="Model_Simulation" Caption="Model:Simulation" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription" Caption="PackageDescription" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="PackageReference" Caption="PackageReference" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="Published" Caption="Published" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="Publisher" Caption="Publisher" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="10uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C1" Designator_X_Mil_="1700" Designator_X_mm_="43.18" Designator_Y_Mil_="3400" Designator_Y_mm_="86.36" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="1" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C1" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="10uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="KVMOGCMJ" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="10uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C2" Designator_X_Mil_="4400" Designator_X_mm_="111.76" Designator_Y_Mil_="3100" Designator_Y_mm_="78.74" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="2" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C2" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="10uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="DCQTCEFS" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="0.1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C3" Designator_X_Mil_="4800" Designator_X_mm_="121.92" Designator_Y_Mil_="3100" Designator_Y_mm_="78.74" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="3" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C3" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="0.1uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="DAVTNUPX" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="0.1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C4" Designator_X_Mil_="5100" Designator_X_mm_="129.54" Designator_Y_Mil_="3100" Designator_Y_mm_="78.74" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="4" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C4" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="0.1uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="YWAEEAAN" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="0.1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C5" Designator_X_Mil_="5400" Designator_X_mm_="137.16" Designator_Y_Mil_="3100" Designator_Y_mm_="78.74" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="5" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C5" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="0.1uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="VGQWXPYH" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="0.1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C6" Designator_X_Mil_="5700" Designator_X_mm_="144.78" Designator_Y_Mil_="3100" Designator_Y_mm_="78.74" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="6" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C6" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="0.1uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="XNGJIEXQ" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="0.1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C7" Designator_X_Mil_="6000" Designator_X_mm_="152.4" Designator_Y_Mil_="3100" Designator_Y_mm_="78.74" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="7" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C7" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="0.1uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="XNGVPRBF" UniqueIdPath="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="Albert Gural" CheckedBy="" Comment="0.1uF" CompanyName="" Component_Kind="Standard" ComponentKind="0" CurrentDate="2/2/2014" CurrentTime="12:21:24 PM" Date="" Description="Capacitor &#40;Semiconductor SIM Model&#41;" Designator="C8" Designator_X_Mil_="6300" Designator_X_mm_="160.02" Designator_Y_Mil_="3100" Designator_Y_mm_="78.74" DesignItemId="Cap Semi" Document="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.SchDoc" DocumentName="FPGA-Oscilloscope.SchDoc" DocumentNumber="" DrawnBy="Albert Gural" Engineer="Albert Gural" Footprint="1608&#91;0603&#93;" Height_Mil_="0" Height_mm_="0" ImagePath="" Index="8" ItemGUID="" LatestRevisionDate="29-May-2009" LatestRevisionNote="IPC-7351 Footprint Added." Library_Name="Miscellaneous Devices.IntLib" Library_Reference="Cap Semi" LibRef="Cap Semi" LogicalDesignator="C8" Model_Footprint="Chip Capacitor, Body 1.6x0.8mm, IPC High Density" Model_Signal_Integrity="" Model_Simulation="Semiconductor Capacitor" Models="7" ModifiedDate="2/2/2014" Organization="" PackageDescription="Chip Capacitor" PackageReference="C1206" PartType="0.1uF" PCB3D="" PhysicalPath="FPGA-Oscilloscope" Pins="2" Project="C:&#92;Users&#92;Albert&#92;Documents&#92;GitHub&#92;FPGA-Oscilloscope&#92;Circuit&#92;FPGA-Oscilloscope.PrjPcb" ProjectName="FPGA-Oscilloscope.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="1" RevisionGUID="" Rule="" SheetNumber="1" SheetTotal="1" Signal_Integrity="Cap Semi" Simulation="CAP" SourceLibraryName="Miscellaneous Devices.IntLib" Sub_Parts="1" Time="" Title="FPGA Oscilloscope" UniqueIdName="YQRGCJJD" UniqueIdPath="" Variant="" VaultGUID=""></ROW>